name: Build & Release Extension

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:
        inputs:
            version:
                description: 'Version (vd: v1.0.0)'
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y chromium-browser
                  npm install chrome-webstore-upload-cli

            - name: Set version
              run: |
                  if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                    echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
                  else
                    echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
                  fi

            - name: Update manifest version
              run: |
                  VERSION_NUMBER=$(echo $VERSION | sed 's/v//')
                  jq ".version = \"$VERSION_NUMBER\"" manifest.json > manifest.json.tmp
                  mv manifest.json.tmp manifest.json

            - name: Create extension files
              run: |
                  mkdir -p build
                  cp manifest.json background.js content.js build/

            - name: Create ZIP file
              run: |
                  cd build
                  zip -r ../extension.zip *
                  cd ..

            - name: Generate .crx file
              run: |
                  if [ ! -f ./private.pem ]; then
                    openssl genrsa -out private.pem 2048
                  fi
                  chromium-browser --pack-extension=./build --pack-extension-key=./private.pem
                  mv build.crx extension.crx

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      extension.zip
                      extension.crx
                  tag_name: ${{ env.VERSION }}
                  draft: false
                  prerelease: false
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
