name: Build & Release Extension

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:
        inputs:
            version:
                description: 'Version (vd: v1.0.0)'
                required: true
                type: string

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'

            - name: Install dependencies
              run: |
                  if [ -f "package.json" ]; then
                    npm install
                  else
                    echo "No package.json found, skipping npm install"
                  fi

            - name: Set version
              run: |
                  if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                    echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
                  else
                    echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
                  fi

            - name: Update manifest version
              run: |
                  VERSION_NUMBER=$(echo $VERSION | sed 's/v//')
                  jq ".version = \"$VERSION_NUMBER\"" manifest.json > manifest.json.tmp
                  mv manifest.json.tmp manifest.json

            - name: Run linting
              run: |
                  if [ -f "package.json" ]; then
                    npm run lint || true
                  fi

            - name: Create extension files
              run: |
                  mkdir -p build
                  cp manifest.json background.js content.js popup.html popup.js build/
                  if [ -d "icons" ]; then
                    cp -r icons build/
                  fi

            - name: Create ZIP file
              run: |
                  cd build
                  zip -r ../extension.zip *
                  cd ..

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      extension.zip
                  tag_name: ${{ env.VERSION }}
                  draft: false
                  prerelease: false
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
